-- Create Nominees Table
CREATE TABLE IF NOT EXISTS nominees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    name TEXT NOT NULL,
    sub_text TEXT,
    image_url TEXT,
    vote_count INTEGER DEFAULT 0,
    CONSTRAINT unique_nominee UNIQUE(category, name)
);

-- Create Votes Table
CREATE TABLE IF NOT EXISTS votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address TEXT NOT NULL,
    category TEXT NOT NULL,
    nominee_name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_votes_rate_limit ON votes (ip_address, category, created_at);
CREATE INDEX IF NOT EXISTS idx_nominees_cat_name ON nominees (category, name);

-- Atomic increment function
CREATE OR REPLACE FUNCTION increment_vote(row_id BIGINT)
RETURNS VOID AS $$
BEGIN
  UPDATE nominees
  SET vote_count = vote_count + 1
  WHERE id = row_id;
END;
$$ LANGUAGE plpgsql;
