-- DANGER: This drops existing tables to ensure a clean slate.
DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS nominees;

-- Create Nominees Table
CREATE TABLE nominees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    name TEXT NOT NULL,
    sub_text TEXT,
    image_url TEXT,
    vote_count INTEGER DEFAULT 0,
    CONSTRAINT unique_nominee UNIQUE(category, name)
);

-- Create Votes Table
CREATE TABLE votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address TEXT NOT NULL,
    category TEXT NOT NULL,
    nominee_name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX idx_votes_rate_limit ON votes (ip_address, category, created_at);
CREATE INDEX idx_nominees_cat_name ON nominees (category, name);
